name: CI_CD
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm install
      - name: Install build
        run: npm run build-front
      - name: test
        run: npm test